version: "3.9"

services:
  backend:
    build:
      context: ./image-app-backend
    ports:
      - "3001:3001"
    env_file:
      - ./image-app-backend/.env
    volumes:
      - ./image-app-backend:/app
      - /app/node_modules
    restart: unless-stopped
