services:
  - type: web
    name: image-app-backend
    env: docker
    rootDir: image-app-backend
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    autoDeploy: true
