services:
  - type: web
    name: image-app-backend
    env: docker
    dockerfilePath: ./image-app-backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    autoDeploy: true
