services:
  - type: web
    name: image-app-backend
    env: docker
    
    rootDir: image-app-backend 
    
    dockerfilePath: /docker-compose.yml
    buildCommand: docker-compose build backend
   
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    autoDeploy: true